const KASPI_BASE=String(process.env.KASPI_API_BASE_URL||'https://kaspi.kz/shop/api/v2').replace(/\/$/,'');
const MAX_CODES=20,CONCURRENCY=3;
function token(){return String(process.env.KASPI_API_TOKEN||process.env.KASPI_TOKEN||process.env.KASPI_API_KEY||'').trim()}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function clean(v){return String(v==null?'':v).trim().replace(/^['"`]+|['"`,;]+$/g,'').replace(/\s+/g,'')}
function candidates(raw){const v=clean(raw),a=[v];if(/-1$/i.test(v))a.push(v.replace(/-1$/i,''));return[...new Set(a.filter(Boolean))]}
function waybill(v){const u=String(v||'').trim();if(!u)return'';if(/^https?:\/\//i.test(u))return u;if(u.startsWith('/'))return'https://kaspi.kz'+u;return u}
function pub(e){return(e instanceof Error?e.message:String(e||'Ошибка')).replace(/X-Auth-Token\s*[:=]\s*\S+/gi,'X-Auth-Token: ***').slice(0,700)}
async function kfetch(path,opt={}){if(!token())throw Error('На Vercel не настроен KASPI_API_TOKEN');let last;for(let i=0;i<3;i++){try{const r=await fetch(KASPI_BASE+path,{method:opt.method||'GET',headers:{Accept:'application/vnd.api+json','Content-Type':'application/vnd.api+json','X-Auth-Token':token()},body:opt.body?JSON.stringify(opt.body):undefined,cache:'no-store'});const t=await r.text();let j={};try{j=t?JSON.parse(t):{}}catch{j={raw:t.slice(0,500)}}if(!r.ok){const d=j?.message||j?.error||j?.errors?.[0]?.detail||j?.errors?.[0]?.title||'';const e=Error('Kaspi API HTTP '+r.status+(d?': '+d:''));e.status=r.status;throw e}return j}catch(e){last=e;const s=Number(e?.status)||0;if(i>=2||(s&&s!==429&&s<500))break;await sleep(350*(i+1))}}throw last||Error('Kaspi API недоступен')}
async function findOrder(raw){for(const c of candidates(raw)){const q=new URLSearchParams();q.set('filter[orders][code]',c);q.set('page[number]','0');q.set('page[size]','20');const j=await kfetch('/orders?'+q);const a=Array.isArray(j?.data)?j.data:[];const x=a.find(o=>clean(o?.attributes?.code)===c)||a[0];if(x)return x}return null}
async function change(id,attrs){return kfetch('/orders',{method:'POST',body:{data:{type:'orders',id:String(id),attributes:attrs}}})}
function snap(o){const a=o?.attributes||{};return{id:String(o?.id||''),code:clean(a.code),status:String(a.status||''),state:String(a.state||''),preorder:a.preOrder===true,waybill:waybill(a.waybill),waybillNumber:String(a.waybillNumber||'')}}
async function refresh(code,delay=0){if(delay)await sleep(delay);const o=await findOrder(code);return o?snap(o):null}
async function refreshWaybill(code){let s=null;for(let i=0;i<5;i++){if(i)await sleep(700);s=await refresh(code);if(!s||s.waybill)return s}return s}
async function transfer(s,spaces){const j=await change(s.id,{status:'ASSEMBLE',numberOfSpace:String(spaces)});return j?.data?snap(j.data):s}
async function processOrder(raw,spaces,formWaybill){const r={rawCode:clean(raw),code:'',id:'',statusBefore:'',stateBefore:'',preorder:false,accepted:false,assembled:false,waybill:'',waybillNumber:'',ok:false,message:''};try{const o=await findOrder(raw);if(!o){r.error='NOT_FOUND';r.message='Заказ не найден в Kaspi';return r}let s=snap(o);Object.assign(r,{code:s.code||r.rawCode,id:s.id,statusBefore:s.status,stateBefore:s.state,preorder:s.preorder,waybill:s.waybill,waybillNumber:s.waybillNumber});if(s.waybill){r.accepted=true;r.assembled=true;r.ok=true;r.message='Уже в «Передача», накладная сформирована';return r}const terminal=new Set(['COMPLETED','CANCELLED','CANCELLING','RETURNED','KASPI_DELIVERY_RETURN_REQUESTED']);if(terminal.has(s.status)){r.error='INVALID_STATUS';r.message='Нельзя обработать заказ со статусом '+s.status;return r}if(s.status==='APPROVED_BY_BANK'||s.state==='NEW'){const j=await change(s.id,{code:s.code||r.code,status:'ACCEPTED_BY_MERCHANT'});if(j?.data)s={...s,...snap(j.data)};r.accepted=true;const x=await refresh(r.code,350);if(x)s=x}else if(['ACCEPTED_BY_MERCHANT','ARRIVED','ASSEMBLE'].includes(s.status)||s.state==='KASPI_DELIVERY'){r.accepted=true}else{r.error='INVALID_STATUS';r.message='Текущий статус '+(s.status||s.state||'неизвестен')+' не подходит для обработки';return r}if(!formWaybill){r.ok=true;r.message='Заказ принят';return r}if(s.status==='ASSEMBLE'){r.assembled=true;const x=await refreshWaybill(r.code);if(x){r.waybill=x.waybill||'';r.waybillNumber=x.waybillNumber||''}r.ok=true;r.message=r.waybill?'Уже в «Передача», накладная сформирована':'Заказ уже в «Передача»; Kaspi готовит накладную';return r}
// По требованию магазина: сразу пробуем перевод в «Передача» для любого принятого заказа,
// включая предзаказы. Плановые даты здесь не блокируют попытку; окончательное решение принимает Kaspi API.
try{s=await transfer(s,spaces);r.assembled=true;r.waybill=s.waybill||r.waybill;r.waybillNumber=s.waybillNumber||r.waybillNumber}catch(e){r.error=pub(e);r.message='Kaspi отклонил прямой перевод в «Передача»: '+r.error;return r}
if(!r.waybill){const x=await refreshWaybill(r.code);if(x){r.waybill=x.waybill||'';r.waybillNumber=x.waybillNumber||''}}
r.ok=true;r.message=r.waybill?'Принят → Передача → накладная сформирована':'Заказ переведён в «Передача»; Kaspi ещё готовит ссылку на накладную';return r}catch(e){r.error=pub(e);r.message=r.error;return r}}
async function mapLimit(a,n,fn){const out=new Array(a.length);let p=0;async function w(){while(true){const i=p++;if(i>=a.length)return;out[i]=await fn(a[i],i)}}await Promise.all(Array.from({length:Math.min(n,a.length)},w));return out}
module.exports=async function(req,res){res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, max-age=0');if(req.method==='GET'){const c=clean(req.query?.code);if(c&&token()){try{const o=await findOrder(c);return res.status(200).json({ok:true,configured:true,order:o?snap(o):null})}catch(e){return res.status(502).json({ok:false,configured:true,error:pub(e)})}}return res.status(200).json({ok:true,configured:Boolean(token()),maxCodesPerRequest:MAX_CODES,provider:'Kaspi Shop API v2',behavior:'immediate-direct-transfer-attempt'})}if(req.method!=='POST'){res.setHeader('Allow','GET, POST');return res.status(405).json({ok:false,error:'Method not allowed'})}if(!token())return res.status(503).json({ok:false,error:'На Vercel не настроен KASPI_API_TOKEN'});let b=req.body||{};if(typeof b==='string'){try{b=JSON.parse(b)}catch{b={}}}const codes=[...new Set((Array.isArray(b.codes)?b.codes:[]).map(clean).filter(Boolean))].slice(0,MAX_CODES);if(!codes.length)return res.status(400).json({ok:false,error:'Не переданы номера заказов'});const spaces=Math.min(20,Math.max(1,parseInt(b.numberOfSpace,10)||1)),formWaybill=b.formWaybill!==false,startedAt=Date.now();const results=await mapLimit(codes,CONCURRENCY,c=>processOrder(c,spaces,formWaybill));const summary={total:results.length,found:results.filter(x=>x.id).length,accepted:results.filter(x=>x.accepted).length,assembled:results.filter(x=>x.assembled).length,waybills:results.filter(x=>x.waybill).length,failed:results.filter(x=>!x.ok).length};return res.status(200).json({ok:summary.failed===0,summary,results,durationMs:Date.now()-startedAt})};
