const KASPI_BASE=String(process.env.KASPI_API_BASE_URL||'https://kaspi.kz/shop/api/v2').replace(/\/$/,'');
const DAY=86400000;
const ALLOWED_ORIGINS=new Set(['https://grants-book-kaspi-assistant.vercel.app','https://grants-book-kaspi-assistant-dias10.vercel.app']);
function token(){return String(process.env.KASPI_API_TOKEN||process.env.KASPI_TOKEN||process.env.KASPI_API_KEY||'').trim()}
function clean(v){return String(v==null?'':v).trim().replace(/-1$/,'')}
function errText(e){return (e instanceof Error?e.message:String(e||'Ошибка')).slice(0,600)}
function cors(req,res){const origin=String(req.headers&&req.headers.origin||'');if(ALLOWED_ORIGINS.has(origin))res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');return origin}
async function kfetch(path,opt={}){const t=token();if(!t)throw Error('KASPI_API_TOKEN не настроен');const r=await fetch(KASPI_BASE+path,{method:opt.method||'GET',headers:{Accept:'application/vnd.api+json','Content-Type':'application/vnd.api+json','X-Auth-Token':t},body:opt.body?JSON.stringify(opt.body):undefined,cache:'no-store'});const text=await r.text();let j={};try{j=text?JSON.parse(text):{}}catch{j={raw:text.slice(0,300)}}if(!r.ok){const d=j?.errors?.[0]?.detail||j?.errors?.[0]?.title||j?.message||j?.error||'';throw Error('Kaspi API '+r.status+(d?': '+d:''))}return j}
function localDay(ms){if(!Number(ms))return'';const d=new Date(Number(ms)+5*3600000);return d.toISOString().slice(0,10)}
function nested(a){return a?.kaspiDelivery&&typeof a.kaspiDelivery==='object'?a.kaspiDelivery:{}}
function deadline(a){const kd=nested(a),tx=Number(kd.courierTransmissionPlanningDate||a.courierTransmissionPlanningDate)||0;if(tx)return{date:localDay(tx-DAY),source:'courierTransmissionPlanningDate'};const r=Number(a.reservationDate)||0;if(r)return{date:localDay(r),source:'reservationDate'};return{date:'',source:''}}
function snap(o){const a=o?.attributes||{},kd=nested(a),dl=deadline(a);return{id:String(o?.id||''),code:clean(a.code),status:String(a.status||''),state:String(a.state||''),preOrder:a.preOrder===true,isKaspiDelivery:a.isKaspiDelivery===true,deliveryMode:String(a.deliveryMode||''),city:String(a.deliveryAddress?.town||''),totalPrice:Number(a.totalPrice)||0,creationDate:Number(a.creationDate)||0,plannedDeliveryDate:Number(a.plannedDeliveryDate)||0,reservationDate:Number(a.reservationDate)||0,courierTransmissionPlanningDate:Number(kd.courierTransmissionPlanningDate||a.courierTransmissionPlanningDate)||0,waybill:String(kd.waybill||a.waybill||''),arrivalDate:dl.date,arrivalSource:dl.source}}
async function findOrder(code){const q=new URLSearchParams();q.set('filter[orders][code]',clean(code));const j=await kfetch('/orders?'+q.toString());return Array.isArray(j.data)?j.data[0]||null:null}
async function listWindow(from,to){const out=[];let page=0;while(page<12){const q=new URLSearchParams();q.set('page[number]',String(page));q.set('page[size]','100');q.set('filter[orders][state]','KASPI_DELIVERY');q.set('filter[orders][creationDate][$ge]',String(from));q.set('filter[orders][creationDate][$le]',String(to));q.set('filter[orders][status]','ACCEPTED_BY_MERCHANT');const j=await kfetch('/orders?'+q.toString());const rows=Array.isArray(j.data)?j.data:[];out.push(...rows);const pc=Math.max(1,Number(j?.meta?.pageCount)||1);if(page+1>=pc||rows.length<100)break;page++}return out}
async function listPreorders(){const now=Date.now();const windows=[{from:now-13*DAY,to:now},{from:now-27*DAY,to:now-13*DAY-1}];const parts=[];for(const w of windows){try{parts.push(await listWindow(w.from,w.to))}catch(e){console.warn('preorder window',new Date(w.from).toISOString(),errText(e))}}const m=new Map();for(const o of parts.flat()){const s=snap(o);if(!s.id||!s.preOrder||s.state!=='KASPI_DELIVERY'||s.status!=='ACCEPTED_BY_MERCHANT'||s.waybill)continue;m.set(s.id,s)}return[...m.values()].sort((a,b)=>(a.arrivalDate||'9999').localeCompare(b.arrivalDate||'9999')||a.code.localeCompare(b.code,'ru',{numeric:true}))}
async function markArrived(code){const o=await findOrder(code);if(!o)throw Error('Заказ не найден');const s=snap(o);if(!s.preOrder)throw Error('Заказ не является предзаказом');if(s.status==='ARRIVED')return{...s,ok:true,arrived:true,message:'Уже отмечен «Прибыл»'};if(s.status!=='ACCEPTED_BY_MERCHANT')throw Error('Нельзя отметить «Прибыл»: текущий статус '+s.status);const j=await kfetch('/orders',{method:'POST',body:{data:{type:'orders',id:s.id,attributes:{code:s.code,status:'ARRIVED'}}}});const changed=j?.data?snap(j.data):null;return{...(changed||s),ok:true,arrived:true,message:'Товар отмечен «Прибыл»'}}
module.exports=async function(req,res){const origin=cors(req,res);res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, max-age=0');if(req.method==='OPTIONS')return res.status(204).end();try{if(req.method==='GET'){if(!token())return res.status(503).json({ok:false,error:'KASPI_API_TOKEN не настроен'});const orders=await listPreorders();return res.status(200).json({ok:true,generatedAt:new Date().toISOString(),orders,count:orders.length})}if(req.method!=='POST'){res.setHeader('Allow','GET, POST, OPTIONS');return res.status(405).json({ok:false,error:'Method not allowed'})}if(origin&&!ALLOWED_ORIGINS.has(origin))return res.status(403).json({ok:false,error:'Недопустимый источник запроса'});let body=req.body||{};if(typeof body==='string'){try{body=JSON.parse(body)}catch{body={}}}if(body.action==='arrived'){const result=await markArrived(body.code);return res.status(200).json({ok:true,result})}if(body.action==='changeDate'){return res.status(409).json({ok:false,code:'DATE_CHANGE_REQUIRES_CABINET',error:'Kaspi не публикует API для изменения планируемой даты прибытия Kaspi Доставки. Используйте кабинет продавца.',cabinetUrl:'https://kaspi.kz/mc/',orderCode:clean(body.code)})}return res.status(400).json({ok:false,error:'Неизвестное действие'})}catch(e){console.error('preorder-dates',e);return res.status(502).json({ok:false,error:errText(e)})}}
